### ISSUE TITLE
in mysql,run example is error!

### ISSUE THREAD

**Issue by fqtyfz** [ebean-orm/avaje-ebeanorm-examples#4]
14:51:08.232 [main] ERROR com.avaje.ebean.Ebean - Error trying to create the default EbeanServer
javax.persistence.PersistenceException: Error: Error executing stmt[create table o_address ( id                            bigint auto_increment not null, line1                         varchar(100), line2                         varchar(100), city                          varchar(100), country_code                  varchar(2), version                       bigint not null, when_created                  datetime(6) not null, when_updated                  datetime(6) not null, constraint pk_o_address primary key (id) )] error[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null, when_updated                  datetime(6) not null, constraint pk_' at line 1]
    at com.avaje.ebean.dbmigration.DdlRunner.runStatements(DdlRunner.java:59) ~[classes/:na]

 when_updated                  datetime(6) not null, is wrong!
right,like this.
 when_updated                  datetime not null,

**Comment by fqtyfz** [comment]
in  com.avaje.ebean.config.dbplatform.MySqlPlatform,
in line 44, dbTypeMap.put(Types.TIMESTAMP, new DbType("datetime(6)"));
modify it ,like this:
dbTypeMap.put(Types.TIMESTAMP, new DbType("datetime"));

is right!

**Comment by rbygrave** [comment]
Update your mysql database version ... The later version supports
datetime(6) with improved precision.

**Comment by fqtyfz** [comment]
okey,is right!

**Comment by rbygrave** [comment]
Ok, closing.
